name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'src/pages/**'
      - 'src/shared/**'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NEXT_ENV: ${{ secrets.NEXT_ENV }}
      NEXT_PUBLIC_RELAY_URL: ${{ secrets.NEXT_PUBLIC_RELAY_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: |
          npm run build:ui

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
