name: Terraform Apply

permissions:
  contents: read
  id-token: write

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      GCP_SA_KEY_PATH: $HOME/gcp-key.json
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_TERRAFORM_SA_KEY: ${{ secrets.GCP_TERRAFORM_SA_KEY }}
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_region: ${{ secrets.GCP_REGION }}
      TF_VAR_service_name: ${{ secrets.CLOUD_RUN_SERVICE }}
      TF_VAR_container_image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.CLOUD_RUN_SERVICE }}:latest
      TF_VAR_cloud_run_service_account_email: ${{ secrets.GCP_COMPUTE_SA_EMAIL }}
      TF_VAR_node_env: ${{ secrets.NODE_ENV }}
      TF_VAR_google_user_account: ${{ secrets.GOOGLE_USER_ACCOUNT }}
      TF_VAR_google_client_id: ${{ secrets.GOOGLE_CLIENT_ID }}
      TF_VAR_google_client_secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      TF_VAR_google_refresh_token: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
      TF_VAR_destination_email: ${{ secrets.DESTINATION_EMAIL }}
      TF_VAR_origins_file_path: ${{ secrets.ORIGINS_FILE_PATH }}
      TF_VAR_bucket_name: ${{ secrets.GCP_BUCKET_NAME }}
      TF_VAR_gh_actions_service_account_email: ${{ secrets.GH_ACTIONS_SA_EMAIL }}
      TF_VAR_commit_sha: ${{ github.sha }}

    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GCP_TERRAFORM_SA_KEY}}

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ env.TF_VAR_service_name }}-${{ env.TF_VAR_bucket_name }}"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
